import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Tu rifa',
  description: 'Generated by create next app',
};

const layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <header>Tu rifa menu</header>
        {children}
        <footer>Tu rifa footer</footer>
      </body>
    </html>
  );
};

export default layout;
