import type { Metadata } from 'next';
import GlobalHeader from '@/components/GlobalHeader/GlobalHeader';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { NextUIProvider } from '@nextui-org/react';

export const metadata: Metadata = {
  title: 'Lucky 9',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased mt-[60px]`}>
        <script
          type='module'
          defer
          src='https://cdn.jsdelivr.net/npm/ldrs/dist/auto/spiral.js'
        ></script>
        <NextUIProvider>
          <ToastContainer
            theme='colored'
            draggable
            className='md:w-[600px]'
            containerId='globalToastify'
          />
          <GlobalHeader />

          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
